/**
 * Test-only secp256k1 key and self-signed certificate (generated with
 * `openssl ecparam -name secp256k1` / `openssl req -x509`). Not a ZATCA CSID.
 */
export const TEST_PRIVATE_KEY = `-----BEGIN EC PRIVATE KEY-----
MHQCAQEEIGfGbHR1KeRdWVtLO3JVTTLjKS5mHEcGMkaDogiv3Q9XoAcGBSuBBAAK
oUQDQgAEJLk+o9eULJ53Rp3VmIMBR6AxbU9IMSAHx026eCFTxwzlxMxo04YjvH/J
jzSeb4QORa10Pu8kTD710vXkAuNXiQ==
-----END EC PRIVATE KEY-----
`;

export const TEST_CERTIFICATE = `-----BEGIN CERTIFICATE-----
MIIB4TCCAYigAwIBAgIUKggB3AxnVGeKAM0e5MeYXo9ooOMwCgYIKoZIzj0EAwIw
SDELMAkGA1UEBhMCU0ExETAPBgNVBAoMCFRlc3QgRUdTMSYwJAYDVQQDDB1UU1Qt
ODg2NDMxMTQ1LTM5OTk5OTk5OTkwMDAwMzAeFw0yNjEwMDgwOTUzMzdaFw0zNjEw
MDUwOTUzMzdaMEgxCzAJBgNVBAYTAlNBMREwDwYDVQQKDAhUZXN0IEVHUzEmMCQG
A1UEAwwdVFNULTg4NjQzMTE0NS0zOTk5OTk5OTk5MDAwMDMwVjAQBgcqhkjOPQIB
BgUrgQQACgNCAAQkuT6j15QsnndGndWYgwFHoDFtT0gxIAfHTbp4IVPHDOXEzGjT
hiO8f8mPNJ5vhA5FrXQ+7yRMPvXS9eQC41eJo1MwUTAdBgNVHQ4EFgQUs57V5GAq
D2biOsAX7SYZ3JoRY+4wHwYDVR0jBBgwFoAUs57V5GAqD2biOsAX7SYZ3JoRY+4w
DwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBEAiBgsuFhszZQYlkdc5M0
PMR3KquSGDV7vjuFae2DZkPxRAIgPKsvnpLiHTAUbjDJNlR4H9gSonf08D4h0HwZ
/tkvQLU=
-----END CERTIFICATE-----
`;
