import { Entity, Column, Index } from 'typeorm';
import { TenantBaseEntity } from '@shared/entities/tenant-base.entity';

/** received = ورقة قبض (from a customer), issued = ورقة دفع (to a supplier). */
export enum ChequeType {
  RECEIVED = 'received',
  ISSUED = 'issued',
}

export enum ChequeStatus {
  // received cheques
  IN_PORTFOLIO = 'in_portfolio',
  UNDER_COLLECTION = 'under_collection',
  COLLECTED = 'collected',
  ENDORSED = 'endorsed',
  RETURNED = 'returned',
  // issued cheques
  ISSUED = 'issued',
  CLEARED = 'cleared',
  // both
  BOUNCED = 'bounced',
  CANCELLED = 'cancelled',
}

export interface ChequeHistoryEntry {
  date: string;
  action: string;
  userId: string;
  note?: string;
}

/**
 * Cheque / promissory note. Created together with a payment of method
 * "cheque" (which settles invoices and posts to notes receivable/payable);
 * later lifecycle steps post from the notes accounts to the bank.
 */
@Entity('cheques')
@Index(['tenantId', 'dueDate'])
export class Cheque extends TenantBaseEntity {
  @Column({ type: 'enum', enum: ChequeType })
  type: ChequeType;

  @Column({ type: 'enum', enum: ChequeStatus })
  status: ChequeStatus;

  @Column({ name: 'cheque_number' })
  chequeNumber: string;

  @Column({ name: 'bank_name', nullable: true })
  bankName: string;

  @Column({ name: 'bank_branch', nullable: true })
  bankBranch: string;

  /** Who signed the cheque. */
  @Column({ nullable: true })
  drawer: string;

  @Column({ name: 'issue_date', type: 'date' })
  issueDate: string;

  @Column({ name: 'due_date', type: 'date' })
  dueDate: string;

  @Column({ type: 'decimal', precision: 18, scale: 4 })
  amount: number;

  @Column({ name: 'currency_id', type: 'uuid', nullable: true })
  currencyId: string;

  @Column({ name: 'exchange_rate', type: 'decimal', precision: 12, scale: 6, default: 1 })
  exchangeRate: number;

  /** 'customer' | 'supplier' */
  @Column({ name: 'partner_type' })
  partnerType: string;

  @Column({ name: 'partner_id', type: 'uuid' })
  partnerId: string;

  /** The payment that created the cheque. */
  @Column({ name: 'payment_id', type: 'uuid' })
  paymentId: string;

  /**
   * Issued cheques: the bank account it is drawn on. Received cheques: the
   * bank it was deposited in / collected into.
   */
  @Column({ name: 'treasury_id', type: 'uuid', nullable: true })
  treasuryId: string;

  @Column({ name: 'endorsed_supplier_id', type: 'uuid', nullable: true })
  endorsedSupplierId: string;

  /** Supplier payment generated by the endorsement. */
  @Column({ name: 'endorsement_payment_id', type: 'uuid', nullable: true })
  endorsementPaymentId: string;

  @Column({ name: 'status_date', type: 'date', nullable: true })
  statusDate: string;

  @Column({ nullable: true })
  notes: string;

  @Column({ type: 'jsonb', default: () => "'[]'" })
  history: ChequeHistoryEntry[];
}
