import { PrintLang } from './document.model';

/** Bilingual labels used by the document builders and renderers. */
export const LABELS = {
  // titles
  taxInvoice: { ar: 'فاتورة ضريبية', en: 'Tax invoice' },
  simplifiedTaxInvoice: { ar: 'فاتورة ضريبية مبسطة', en: 'Simplified tax invoice' },
  creditNote: { ar: 'إشعار دائن', en: 'Credit note' },
  quotation: { ar: 'عرض سعر', en: 'Quotation' },
  salesOrder: { ar: 'أمر بيع', en: 'Sales order' },
  deliveryNote: { ar: 'إذن تسليم', en: 'Delivery note' },
  purchaseOrder: { ar: 'أمر شراء', en: 'Purchase order' },
  rfq: { ar: 'طلب عرض سعر', en: 'Request for quotation' },
  receiptVoucher: { ar: 'سند قبض', en: 'Receipt voucher' },
  paymentVoucher: { ar: 'سند صرف', en: 'Payment voucher' },
  posReceipt: { ar: 'إيصال بيع', en: 'Sales receipt' },
  posRefund: { ar: 'إيصال مرتجع', en: 'Refund receipt' },
  payslip: { ar: 'قسيمة راتب', en: 'Payslip' },
  payrollRegister: { ar: 'مسير الرواتب', en: 'Payroll register' },
  statement: { ar: 'كشف حساب', en: 'Statement of account' },
  cheque: { ar: 'شيك', en: 'Cheque' },
  // header / meta
  number: { ar: 'الرقم', en: 'Number' },
  date: { ar: 'التاريخ', en: 'Date' },
  issueDate: { ar: 'تاريخ الإصدار', en: 'Issue date' },
  dueDate: { ar: 'تاريخ الاستحقاق', en: 'Due date' },
  validUntil: { ar: 'صالح حتى', en: 'Valid until' },
  expectedDate: { ar: 'تاريخ التوريد المتوقع', en: 'Expected date' },
  status: { ar: 'الحالة', en: 'Status' },
  currency: { ar: 'العملة', en: 'Currency' },
  exchangeRate: { ar: 'سعر الصرف', en: 'Exchange rate' },
  reference: { ar: 'المرجع', en: 'Reference' },
  originalInvoice: { ar: 'الفاتورة الأصلية', en: 'Original invoice' },
  orderNumber: { ar: 'رقم الأمر', en: 'Order number' },
  period: { ar: 'الفترة', en: 'Period' },
  from: { ar: 'من', en: 'From' },
  to: { ar: 'إلى', en: 'To' },
  branch: { ar: 'الفرع', en: 'Branch' },
  warehouse: { ar: 'المخزن', en: 'Warehouse' },
  method: { ar: 'طريقة الدفع', en: 'Payment method' },
  treasury: { ar: 'الخزينة / البنك', en: 'Cash box / bank' },
  cashier: { ar: 'الكاشير', en: 'Cashier' },
  page: { ar: 'صفحة', en: 'Page' },
  of: { ar: 'من', en: 'of' },
  printedAt: { ar: 'طبع في', en: 'Printed' },
  taxNumber: { ar: 'الرقم الضريبي', en: 'Tax number' },
  vatNumber: { ar: 'رقم التسجيل الضريبي', en: 'VAT number' },
  commercialRegistration: { ar: 'السجل التجاري', en: 'C.R.' },
  phone: { ar: 'الهاتف', en: 'Phone' },
  email: { ar: 'البريد', en: 'Email' },
  address: { ar: 'العنوان', en: 'Address' },
  // parties
  seller: { ar: 'البائع', en: 'Seller' },
  buyer: { ar: 'المشتري', en: 'Buyer' },
  customer: { ar: 'العميل', en: 'Customer' },
  supplier: { ar: 'المورد', en: 'Supplier' },
  name: { ar: 'الاسم', en: 'Name' },
  code: { ar: 'الكود', en: 'Code' },
  receivedFrom: { ar: 'استلمنا من', en: 'Received from' },
  paidTo: { ar: 'صرفنا إلى', en: 'Paid to' },
  employee: { ar: 'الموظف', en: 'Employee' },
  nationalId: { ar: 'الرقم القومي / الإقامة', en: 'ID / Iqama' },
  bank: { ar: 'البنك', en: 'Bank' },
  iban: { ar: 'الآيبان', en: 'IBAN' },
  // table columns
  index: { ar: 'م', en: '#' },
  item: { ar: 'الصنف', en: 'Item' },
  description: { ar: 'البيان', en: 'Description' },
  unit: { ar: 'الوحدة', en: 'Unit' },
  quantity: { ar: 'الكمية', en: 'Qty' },
  ordered: { ar: 'المطلوب', en: 'Ordered' },
  delivered: { ar: 'المسلم', en: 'Delivered' },
  remaining: { ar: 'المتبقي', en: 'Remaining' },
  unitPrice: { ar: 'سعر الوحدة', en: 'Unit price' },
  discount: { ar: 'الخصم', en: 'Discount' },
  taxRate: { ar: 'نسبة الضريبة', en: 'VAT %' },
  taxAmount: { ar: 'مبلغ الضريبة', en: 'VAT amount' },
  lineNet: { ar: 'الصافي', en: 'Net' },
  lineTotal: { ar: 'الإجمالي', en: 'Total' },
  account: { ar: 'الحساب', en: 'Account' },
  amount: { ar: 'المبلغ', en: 'Amount' },
  debit: { ar: 'مدين', en: 'Debit' },
  credit: { ar: 'دائن', en: 'Credit' },
  balance: { ar: 'الرصيد', en: 'Balance' },
  document: { ar: 'المستند', en: 'Document' },
  // totals
  subtotal: { ar: 'الإجمالي قبل الضريبة', en: 'Subtotal (excl. VAT)' },
  totalDiscount: { ar: 'إجمالي الخصم', en: 'Total discount' },
  vatAt: { ar: 'ضريبة القيمة المضافة', en: 'VAT' },
  totalVat: { ar: 'إجمالي الضريبة', en: 'Total VAT' },
  total: { ar: 'الإجمالي شامل الضريبة', en: 'Total (incl. VAT)' },
  grandTotal: { ar: 'الإجمالي', en: 'Total' },
  withholding: { ar: 'ضريبة الخصم والإضافة', en: 'Withholding tax' },
  paid: { ar: 'المدفوع', en: 'Paid' },
  due: { ar: 'المتبقي', en: 'Balance due' },
  cashReceived: { ar: 'النقدية المستلمة', en: 'Cash received' },
  change: { ar: 'الباقي', en: 'Change' },
  openingBalance: { ar: 'الرصيد الافتتاحي', en: 'Opening balance' },
  closingBalance: { ar: 'الرصيد الختامي', en: 'Closing balance' },
  totalDebit: { ar: 'إجمالي المدين', en: 'Total debit' },
  totalCredit: { ar: 'إجمالي الدائن', en: 'Total credit' },
  amountInWords: { ar: 'المبلغ بالحروف', en: 'Amount in words' },
  // payroll
  earnings: { ar: 'الاستحقاقات', en: 'Earnings' },
  deductions: { ar: 'الاستقطاعات', en: 'Deductions' },
  basic: { ar: 'الراتب الأساسي', en: 'Basic salary' },
  allowances: { ar: 'البدلات', en: 'Allowances' },
  overtime: { ar: 'الإضافي', en: 'Overtime' },
  additions: { ar: 'إضافات أخرى', en: 'Other additions' },
  gross: { ar: 'إجمالي الاستحقاقات', en: 'Gross pay' },
  attendanceDeductions: { ar: 'خصومات الحضور والغياب', en: 'Attendance deductions' },
  employeeSi: { ar: 'التأمينات الاجتماعية (حصة الموظف)', en: 'Social insurance (employee)' },
  employerSi: { ar: 'التأمينات (حصة صاحب العمل)', en: 'Social insurance (employer)' },
  incomeTax: { ar: 'ضريبة كسب العمل', en: 'Income tax' },
  loans: { ar: 'أقساط السلف', en: 'Loan installments' },
  otherDeductions: { ar: 'خصومات أخرى', en: 'Other deductions' },
  totalDeductions: { ar: 'إجمالي الاستقطاعات', en: 'Total deductions' },
  netPay: { ar: 'صافي الراتب', en: 'Net pay' },
  employees: { ar: 'عدد الموظفين', en: 'Employees' },
  // compliance
  etaUuid: { ar: 'الرقم الإلكتروني (ETA)', en: 'ETA UUID' },
  etaStatus: { ar: 'حالة منظومة الفاتورة الإلكترونية', en: 'ETA status' },
  etaUrl: { ar: 'رابط التحقق', en: 'Verification URL' },
  zatcaQr: { ar: 'رمز الاستجابة السريعة - هيئة الزكاة والضريبة والجمارك', en: 'ZATCA QR code' },
  etaQr: { ar: 'امسح للتحقق من الفاتورة', en: 'Scan to verify' },
  zatcaUuid: { ar: 'المعرف الفريد (UUID)', en: 'UUID' },
  // signatures
  preparedBy: { ar: 'إعداد', en: 'Prepared by' },
  approvedBy: { ar: 'اعتماد', en: 'Approved by' },
  receivedBy: { ar: 'المستلم', en: 'Received by' },
  accountant: { ar: 'المحاسب', en: 'Accountant' },
  cashierSign: { ar: 'أمين الخزينة', en: 'Cashier' },
  storekeeper: { ar: 'أمين المخزن', en: 'Storekeeper' },
  employeeSign: { ar: 'توقيع الموظف', en: 'Employee signature' },
  customerSign: { ar: 'توقيع العميل', en: 'Customer signature' },
  notes: { ar: 'ملاحظات', en: 'Notes' },
  thankYou: { ar: 'شكراً لتعاملكم معنا', en: 'Thank you for your business' },
} satisfies Record<string, { ar: string; en: string }>;

export type LabelKey = keyof typeof LABELS;

/** Label getter bound to a language. */
export function labels(lang: PrintLang) {
  return (key: LabelKey) => LABELS[key][lang];
}

/** Bilingual enum values (statuses, methods...). */
const VALUES: Record<string, { ar: string; en: string }> = {
  draft: { ar: 'مسودة', en: 'Draft' },
  posted: { ar: 'مرحل', en: 'Posted' },
  sent: { ar: 'مرسل', en: 'Sent' },
  paid: { ar: 'مدفوع', en: 'Paid' },
  partial: { ar: 'مدفوع جزئياً', en: 'Partially paid' },
  overdue: { ar: 'متأخر', en: 'Overdue' },
  cancelled: { ar: 'ملغي', en: 'Cancelled' },
  confirmed: { ar: 'مؤكد', en: 'Confirmed' },
  delivered: { ar: 'تم التسليم', en: 'Delivered' },
  received: { ar: 'تم الاستلام', en: 'Received' },
  to_approve: { ar: 'بانتظار الاعتماد', en: 'To approve' },
  approved: { ar: 'معتمد', en: 'Approved' },
  reversed: { ar: 'معكوس', en: 'Reversed' },
  completed: { ar: 'مكتمل', en: 'Completed' },
  refunded: { ar: 'مسترد', en: 'Refunded' },
  void: { ar: 'ملغي', en: 'Void' },
  bounced: { ar: 'مرتد', en: 'Bounced' },
  cash: { ar: 'نقدي', en: 'Cash' },
  bank: { ar: 'تحويل بنكي', en: 'Bank transfer' },
  card: { ar: 'بطاقة', en: 'Card' },
  cheque: { ar: 'شيك', en: 'Cheque' },
  split: { ar: 'نقدي + بطاقة', en: 'Cash + card' },
  valid: { ar: 'صالحة', en: 'Valid' },
  invalid: { ar: 'غير صالحة', en: 'Invalid' },
  submitted: { ar: 'مرسلة', en: 'Submitted' },
  rejected: { ar: 'مرفوضة', en: 'Rejected' },
  reported: { ar: 'تم الإبلاغ', en: 'Reported' },
  cleared: { ar: 'تم الاعتماد', en: 'Cleared' },
  pending: { ar: 'قيد الانتظار', en: 'Pending' },
  invoice: { ar: 'فاتورة', en: 'Invoice' },
  credit_note: { ar: 'إشعار دائن', en: 'Credit note' },
  bill: { ar: 'فاتورة مورد', en: 'Vendor bill' },
  vendor_refund: { ar: 'مرتجع مورد', en: 'Vendor refund' },
  payment: { ar: 'سداد', en: 'Payment' },
  refund: { ar: 'رد مبلغ', en: 'Refund' },
  direct_payment: { ar: 'تسوية', en: 'Settlement' },
};

export function valueLabel(value: string | null | undefined, lang: PrintLang): string {
  if (!value) return '';
  return VALUES[value]?.[lang] ?? value;
}
