import { IsOptional, IsUUID, IsDateString } from 'class-validator';
import { ApiPropertyOptional } from '@nestjs/swagger';

export class UpdateAccountingSettingsDto {
  @ApiPropertyOptional() @IsOptional() @IsUUID() receivableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() payableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() salesAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() purchaseAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() inventoryAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() cogsAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() stockAdjustmentAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() outputTaxAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() inputTaxAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() cashAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() bankAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() retainedEarningsAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() depreciationExpenseAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() accumulatedDepreciationAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() assetDisposalAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() notesReceivableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() chequesUnderCollectionAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() notesPayableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() fxGainAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() fxLossAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() bankChargesAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() withholdingTaxReceivableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() withholdingTaxPayableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() salesReturnAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() salesDiscountAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() salariesExpenseAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() salariesPayableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() socialInsuranceExpenseAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() socialInsurancePayableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() payrollTaxPayableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() employeeAdvancesAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() commissionExpenseAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() commissionPayableAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() installmentInterestAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() manufacturingOverheadAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsUUID() purchaseReturnAccountId?: string;
  @ApiPropertyOptional() @IsOptional() @IsDateString() lockDate?: string;
}
